@startuml
skinparam classAttributeIconSize 0
abstract class Animal{

# kind: String
+ Animal()
+ toString(): String
+ {abstract} speak():String
+ {static} main(args: String[])

}



skinparam classAttributeIconSize 0
interface Trainable{

+ {abstract} doATrick():String

}

@enduml